### ISSUE TITLE
Quotes in Advanced GM Explorer Search Breaks Deletes

### ISSUE THREAD

**Issue by profpandabear** [PokeMiners/website#5]
In trying to search for 1km buddies, I tried searching `"kmBuddyDistance": 1` and it correctly goes into a rounded-pill badge in the search strings div with a `×` at the end, but clicking on the `×` to delete the search string does nothing. I was able to replicate the behavior with this search as well `"kmBuddyDistance"=1`. I also tested with `"kmBuddyDistance: 1` to see if a singular double quote would break the click `×` to delete functionality and it was also broken.

**Comment by profpandabear** [comment]
Tangentially from this issue, I would very much love a way to filter the GM for 1km buddies 🙃

**Comment by marty0678** [comment]
Thank you for this, we were able to reproduce it. We'll close this issue when we get a chance to fix it.

**Comment by marty0678** [comment]
Had a chance to look into this, and the search isn't a string-based search for reference, so quotes like that actually don't work in general (which is why it breaks when removing it). I made it so double quotes are filtered out of the search, but if you are looking for something like that, I would say a simple CTRL+F would give you what you are looking for.

Thanks!
